import { defineConfig } from "vite";

// Relative base + relative asset paths so the built site works when hosted
// under a subpath (apps.charliekrug.com/planscope), not just at a domain root.
export default defineConfig({
  base: "./",
  build: {
    outDir: "dist",
  },
  test: {
    environment: "jsdom",
    coverage: {
      provider: "v8",
      // src/wasm is wasm-bindgen-generated glue (regenerated by
      // scripts/build-wasm.sh, gitignored) - it's not code we own, and its
      // exception-handling branches aren't exercised by unit tests.
      exclude: ["src/wasm/**", "src/vite-env.d.ts", "**/*.config.ts"],
    },
  },
});
